name: Flutter CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      reason:
        description: "Manual run reason"
        required: true
        default: "Triggered manually"

jobs:
  analyze:
    runs-on: [self-hosted, Linux, X64, isa]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Check Flutter
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze
