// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_network_err`, `net`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NetHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Generates a new random Ed25519 keypair.
/// Returns (session_id, secret_key_bytes, seed_hex).
(String, Uint8List, String) generateKeypair() =>
    RustLib.instance.api.crateApiSimpleGenerateKeypair();

/// Derives a keypair from a 16-byte seed.
(String, Uint8List) keypairFromSeed({required List<int> seed}) =>
    RustLib.instance.api.crateApiSimpleKeypairFromSeed(seed: seed);

/// Validates a 66-character hex Session ID.
bool validateSessionId({required String sessionId}) =>
    RustLib.instance.api.crateApiSimpleValidateSessionId(sessionId: sessionId);

/// Signs a message with an Ed25519 secret key. Returns 64-byte signature as hex.
String ed25519Sign({
  required List<int> secretKey,
  required List<int> message,
}) => RustLib.instance.api.crateApiSimpleEd25519Sign(
  secretKey: secretKey,
  message: message,
);

/// Returns the Ed25519 public key (hex) from a 64-byte secret key.
String ed25519PubkeyFromSecret({required List<int> secretKey}) => RustLib
    .instance
    .api
    .crateApiSimpleEd25519PubkeyFromSecret(secretKey: secretKey);

/// Initialises the network orchestrator. Must be called once at app start
/// before any `send_message` / `poll_messages` call.
void initNetwork() => RustLib.instance.api.crateApiSimpleInitNetwork();

/// Sends a 1:1 text message.
///
/// * `sender_ed25519_secret_key` — 64-byte libsodium-style secret key.
/// * `recipient_session_id` — 66-hex-char Session id (`05...`).
/// * `text` — UTF-8 message body.
/// * `timestamp_ms` — message timestamp (usually `now()`).
Future<void> sendMessage({
  required List<int> senderEd25519SecretKey,
  required String recipientSessionId,
  required String text,
  required PlatformInt64 timestampMs,
}) => RustLib.instance.api.crateApiSimpleSendMessage(
  senderEd25519SecretKey: senderEd25519SecretKey,
  recipientSessionId: recipientSessionId,
  text: text,
  timestampMs: timestampMs,
);

/// One-shot message poll: runs an authenticated retrieve over onion routing,
/// decrypts every received envelope, and returns
/// `(sender_session_id, body, timestamp_ms, hash)` for each successfully
/// decrypted message.
///
/// * `my_ed25519_secret_key` — 64-byte secret key.
/// * `my_session_id` — the owner's `05...` id.
/// * `last_hash` — the hash of the last retrieved message (from the previous
///   poll); empty string for "fetch everything".
Future<List<PolledMessage>> pollMessages({
  required List<int> myEd25519SecretKey,
  required String mySessionId,
  required String lastHash,
}) => RustLib.instance.api.crateApiSimplePollMessages(
  myEd25519SecretKey: myEd25519SecretKey,
  mySessionId: mySessionId,
  lastHash: lastHash,
);

/// Returns the libsession crate version.
String libVersion() => RustLib.instance.api.crateApiSimpleLibVersion();

/// One decrypted inbound message, returned by [`poll_messages`].
class PolledMessage {
  /// Snode-assigned message hash (used for `last_hash` on the next poll).
  final String hash;

  /// Sender's Session id (`05...`).
  final String senderSessionId;

  /// Plaintext UTF-8 body.
  final String body;

  /// Timestamp in milliseconds (from the envelope or content).
  final PlatformInt64 timestampMs;

  const PolledMessage({
    required this.hash,
    required this.senderSessionId,
    required this.body,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      hash.hashCode ^
      senderSessionId.hashCode ^
      body.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PolledMessage &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          senderSessionId == other.senderSessionId &&
          body == other.body &&
          timestampMs == other.timestampMs;
}
